### ISSUE TITLE
Passing args cause ruff to stop linting

### ISSUE THREAD

**Issue by ravisumit33** [yaegassy/coc-ruff#12]
I have currently enabled autofix but want some rules to be not autofixable. Ruff provides a setting `--unfixable` exactly for this. I tried setting `ruff.args=["--unfixable F401"]` in `coc-settings.json`. As soon as I add this setting, coc-ruff stops working with no linting and fixing at all.

**Comment by yaegassy** [comment]
I think there is an issue with your configuration, and coc-ruff or coc.nvim itself is not functioning properly.

`ruff.args` is comma-separated array of strings. 

**coc-settings.json**:

```
{
  "ruff.args": ["--unfixable", "F401" ]
}
```
