### ISSUE TITLE
Autofix doesn't save file automatically after fix

### ISSUE THREAD

**Issue by ravisumit33** [yaegassy/coc-ruff#13]
I have `"ruff.autoFixOnSave": true` in my coc settings. Whenever I save my file, ruff applies fixes but doesn't save the file. This behaviour is different from extensions like [coc-eslint](https://github.com/neoclide/coc-eslint) which save the file with the fix applied.

**Comment by yaegassy** [comment]
We have made adjustments to the feature regarding the issue in this ticket. Please update coc-ruff and give it a try.
