### ISSUE TITLE
Adding whitespace before colon

### ISSUE THREAD

**Issue by brad-ley** [yaegassy/coc-ruff#22]
The wrapping of astral-sh/ruff seems to be adding whitespace before colons and triggering the linter E203 after formatting fix. It seems like this was also an issue with astral-sh/ruff, issued here: https://github.com/astral-sh/ruff/issues/8642 and fixed in 2023. Can this be fixed easily by upgrading to a new version of astral-sh?

**Comment by yaegassy** [comment]
Please execute the command to install `ruff-lsp` of `coc-ruff`. The latest version will be reinstalled.

```
:CocCommand ruff.builtin.installServer
```
