### ISSUE TITLE
Support for `formatOnSave`?

### ISSUE THREAD

**Issue by pgiraud** [yaegassy/coc-ruff#26]
Is there any plan to add support for a "Format On Save" feature?

There doesn't seem to be any `ruff.formatOnSave` entry for `coc-settings.json` available.

**Comment by yaegassy** [comment]
Please configure `coc.preferences.formatOnSave` in `coc-settings.json`.

```
{
  // ...snip
  "[python]": {
    "coc.preferences.formatOnSave": true,
  },
  // ...snip
}
```

**Comment by pgiraud** [comment]
Thanks. It works.
